USE ROLE ACCOUNTADMIN;

-- 1. Create clean database and 

CREATE SCHEMA ATMOSYNC_DB.TELEMETRY;

-- 2. Create target table for streaming USE ROLE 
CREATE TABLE ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY (
    RECORD_CONTENT VARIANT,
    RECORD_METADATA VARIANT
);

-- 3. Create role and grant permissions
CREATE ROLE KAFKA_CONNECTOR_ROLE;
GRANT ALL ON DATABASE ATMOSYNC_DB TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT ALL ON SCHEMA ATMOSYNC_DB.TELEMETRY TO ROLE KAFKA_CONNECTOR_ROLE;
USE ROLE ACCOUNTADMIN;

ALTER USER KAFKA_USER SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwlBm5yWMsZw22de2XZcXUW70m40MyyBXMfk3l+uX69D4R8g8wfWxPOmYcz/P52hTs9hr6D/rPK5ZWbCFIulBj/dGOyQ7gzyrbteVr+hRSWk5mmeBK/6AQBfbASMg3qk9V2Yr3Nuo1pPlsu3ypFOB oP8m2SsAVXHUuhYaQIBJRlPKvvitIf5tHBHJealtzH9uLQHCcBPVkHC0inhNa5DXF4tHpnKjHtiUipiRnnUQZDSxqGk2a6CfxBtVscHiJco9ccUTobzK4T+dXVlhXU6X/ZZZ1zXFm+SjIeDhfE4VRNCBa4oGvJ0PMuIkKPdPPQVV6CHOs3nYCam6MUqjhq5+lQIDAQAB';
DESCRIBE USER KAFKA_USER;
SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME() AS MY_ACCOUNT_IDENTIFIER;

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE KAFKA_CONNECTOR_ROLE;
ALTER USER KAFKA_USER SET DEFAULT_WAREHOUSE = COMPUTE_WH;
USE ROLE KAFKA_CONNECTOR_ROLE;
USE DATABASE ATMOSYNC_DB;
USE SCHEMA TELEMETRY;

SELECT COUNT(*) AS TOTAL_RECORDS FROM SENSOR_TELEMETRY;
SELECT * FROM ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY;
USE ROLE KAFKA_CONNECTOR_ROLE;
USE DATABASE ATMOSYNC_DB;
USE SCHEMA TELEMETRY;

CREATE OR REPLACE VIEW V_SENSOR_TELEMETRY AS
SELECT 
    RECORD_CONTENT:Container_ID::STRING         AS CONTAINER_ID,
    RECORD_CONTENT:Commodity::STRING            AS COMMODITY,
    RECORD_CONTENT:Temperature::FLOAT           AS TEMPERATURE_C,
    RECORD_CONTENT:Humidity::FLOAT              AS HUMIDITY_PCT,
    RECORD_CONTENT:Vibration::INT               AS VIBRATION,
    RECORD_CONTENT:Battery::INT                 AS BATTERY_PCT,
    RECORD_CONTENT:Timestamp::TIMESTAMP_NTZ     AS EVENT_TIMESTAMP,
    INSERTED_AT                                 AS LOADED_AT
FROM ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY;
SELECT * FROM V_SENSOR_TELEMETRY ORDER BY EVENT_TIMESTAMP DESC;
-- Step 1: Build the View
CREATE OR REPLACE VIEW ATMOSYNC_DB.TELEMETRY.V_SENSOR_TELEMETRY AS
SELECT 
    RECORD_CONTENT:Container_ID::STRING         AS CONTAINER_ID,
    RECORD_CONTENT:Commodity::STRING            AS COMMODITY,
    RECORD_CONTENT:Temperature::FLOAT           AS TEMPERATURE_C,
    RECORD_CONTENT:Humidity::FLOAT              AS HUMIDITY_PCT,
    RECORD_CONTENT:Vibration::INT               AS VIBRATION,
    RECORD_CONTENT:Battery::INT                 AS BATTERY_PCT,
    RECORD_CONTENT:Timestamp::TIMESTAMP_NTZ     AS EVENT_TIMESTAMP,
    INSERTED_AT                                 AS LOADED_AT
FROM ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY;

-- Step 2: Query the View
SELECT * 
FROM ATMOSYNC_DB.TELEMETRY.V_SENSOR_TELEMETRY 
ORDER BY EVENT_TIMESTAMP DESC;
CREATE OR REPLACE VIEW ATMOSYNC_DB.TELEMETRY.V_SENSOR_TELEMETRY AS
SELECT 
    RECORD_CONTENT:Container_ID::STRING         AS CONTAINER_ID,
    RECORD_CONTENT:Commodity::STRING            AS COMMODITY,
    RECORD_CONTENT:Temperature::FLOAT           AS TEMPERATURE_C,
    RECORD_CONTENT:Humidity::FLOAT              AS HUMIDITY_PCT,
    RECORD_CONTENT:Vibration::INT               AS VIBRATION,
    RECORD_CONTENT:Battery::INT                 AS BATTERY_PCT,
    RECORD_CONTENT:Timestamp::TIMESTAMP_NTZ     AS EVENT_TIMESTAMP,
    INSERTED_AT                                 AS LOADED_AT
FROM ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY;
CREATE OR REPLACE VIEW ATMOSYNC_DB.TELEMETRY.V_SENSOR_TELEMETRY AS
SELECT 
    RECORD_CONTENT:Container_ID::STRING         AS CONTAINER_ID,
    RECORD_CONTENT:Commodity::STRING            AS COMMODITY,
    RECORD_CONTENT:Temperature::FLOAT           AS TEMPERATURE_C,
    RECORD_CONTENT:Humidity::FLOAT              AS HUMIDITY_PCT,
    RECORD_CONTENT:Vibration::INT               AS VIBRATION,
    RECORD_CONTENT:Battery::INT                 AS BATTERY_PCT,
    RECORD_CONTENT:Timestamp::TIMESTAMP_NTZ     AS EVENT_TIMESTAMP
FROM ATMOSYNC_DB.TELEMETRY.SENSOR_TELEMETRY;
SELECT * 
FROM ATMOSYNC_DB.TELEMETRY.V_SENSOR_TELEMETRY 
ORDER BY EVENT_TIMESTAMP DESC;
USE ROLE ACCOUNTADMIN;
CREATE SCHEMA IF NOT EXISTS ATMOSYNC_DB.TRANSFORMED;
GRANT ALL PRIVILEGES ON SCHEMA ATMOSYNC_DB.TRANSFORMED TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA ATMOSYNC_DB.TELEMETRY TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ATMOSYNC_DB.TELEMETRY TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA ATMOSYNC_DB.TRANSFORMED TO ROLE KAFKA_CONNECTOR_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA ATMOSYNC_DB.TELEMETRY TO ROLE KAFKA_CONNECTOR_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ATMOSYNC_DB.TELEMETRY TO ROLE KAFKA_CONNECTOR_ROLE;
USE ROLE ACCOUNTADMIN;
GRANT ROLE KAFKA_CONNECTOR_ROLE TO USER HARISH29;
